### ISSUE TITLE
rpm is not in the yum repo

### ISSUE THREAD

**Issue by andreaspeters** [bitwiseworks/qtsvg-os2#1]
Hi,

its not a bug at all. But the rpm files of the qt5-svg and the qt5-tools are not in the yum repo. So, if you write how to install the moduls via yum, it would be also nice if they are available there. :-) Or does u have a special bitwise rpm repository? :-) 

Kind Regards,
Andreas

**Comment by SilvanScherrer** [comment]
Did you enable the netlabs-exp repository? As they are not moved to netlabs-rel so far.

**Comment by andreaspeters** [comment]
No I didn't. Can u tell me the Url of the Repo? :-)

**Comment by SilvanScherrer** [comment]
yum install netlabs-exp

**Comment by andreaspeters** [comment]
Perfect, thanks Silvan.
